name: Claude Code - PR Review
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  claude-code-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: anthropics/claude-code-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          mode: pr-review
